// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QbitFlow.Infrastructure.Data;

#nullable disable

namespace QbitFlow.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260904050839_FlattenModel")]
    partial class FlattenModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.19");

            modelBuilder.Entity("QbitFlow.Core.Domain.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("QbitFlow.Core.Domain.MediaFilePath", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FileName");

                    b.HasIndex("MediaItemId");

                    b.ToTable("MediaFilePaths");
                });

            modelBuilder.Entity("QbitFlow.Core.Domain.MediaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastWatchedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<double>("LegacyScore")
                        .HasColumnType("REAL");

                    b.Property<string>("MatchKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Rating")
                        .HasColumnType("REAL");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<double>("WeightedWatchTotal")
                        .HasColumnType("REAL");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MatchKey");

                    b.ToTable("MediaItems");
                });

            modelBuilder.Entity("QbitFlow.Core.Domain.MediaScoreCache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ComputedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("DaysSinceLastWatched")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsMediaMatched")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("MediaItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QbtInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TorrentHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("WatchPopularity")
                        .HasColumnType("REAL");

                    b.Property<double>("WatchTotal")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("QbtInstanceId", "TorrentHash")
                        .IsUnique();

                    b.ToTable("MediaScoreCache");
                });

            modelBuilder.Entity("QbitFlow.Core.Domain.MediaSourceStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("FetchedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastPlayedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MediaItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SourceConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("SourceRating")
                        .HasColumnType("REAL");

                    b.Property<string>("WindowCountsJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId", "SourceConnectionId")
                        .IsUnique();

                    b.ToTable("MediaSourceStats");
                });

            modelBuilder.Entity("QbitFlow.Core.Domain.Rule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompileError")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CompileValid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompiledExpression")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CompiledUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConditionMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CooldownSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawExpression")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RootGroupId")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("StopOnMatch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetFilterJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Order");

                    b.HasIndex("RootGroupId");

                    b.ToTable("Rules");
                });

            modelBuilder.Entity("QbitFlow.Core.Domain.RuleAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParamsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RuleId")
                        .IsUnique();

                    b.ToTable("RuleActions");
                });

            modelBuilder.Entity("QbitFlow.Core.Domain.RuleCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("RuleConditions");
                });

            modelBuilder.Entity("QbitFlow.Core.Domain.RuleConditionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Logic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ParentGroupId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentGroupId");

                    b.ToTable("RuleConditionGroups");
                });

            modelBuilder.Entity("QbitFlow.Core.Domain.RunHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ActionsApplied")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActionsSkipped")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActionsWouldApply")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DryRun")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FinishedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RulesEvaluated")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SummaryJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("TorrentsEvaluated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StartedUtc");

                    b.ToTable("RunHistory");
                });

            modelBuilder.Entity("QbitFlow.Core.Domain.RunLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RuleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Seq")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TimestampUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TorrentHash")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "Seq");

                    b.ToTable("RunLogEntries");
                });

            modelBuilder.Entity("QbitFlow.Core.Domain.RunRuleResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ActionsApplied")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActionsWouldApply")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FailureCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("RunRuleResults");
                });

            modelBuilder.Entity("QbitFlow.Core.Domain.ScriptRunMarker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RunDir")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TorrentHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RuleId", "TorrentHash")
                        .IsUnique();

                    b.ToTable("ScriptRunMarkers");
                });

            modelBuilder.Entity("QbitFlow.Core.Domain.SourceConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HealthState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastCheckedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<byte[]>("SecretCiphertext")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("SecretNonce")
                        .HasColumnType("BLOB");

                    b.Property<long>("UpdatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SourceConnections");
                });

            modelBuilder.Entity("QbitFlow.Core.Domain.MediaFilePath", b =>
                {
                    b.HasOne("QbitFlow.Core.Domain.MediaItem", "MediaItem")
                        .WithMany("Files")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("QbitFlow.Core.Domain.MediaSourceStat", b =>
                {
                    b.HasOne("QbitFlow.Core.Domain.MediaItem", "MediaItem")
                        .WithMany("SourceStats")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("QbitFlow.Core.Domain.Rule", b =>
                {
                    b.HasOne("QbitFlow.Core.Domain.RuleConditionGroup", "RootGroup")
                        .WithMany()
                        .HasForeignKey("RootGroupId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("RootGroup");
                });

            modelBuilder.Entity("QbitFlow.Core.Domain.RuleAction", b =>
                {
                    b.HasOne("QbitFlow.Core.Domain.Rule", "Rule")
                        .WithOne("Action")
                        .HasForeignKey("QbitFlow.Core.Domain.RuleAction", "RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("QbitFlow.Core.Domain.RuleCondition", b =>
                {
                    b.HasOne("QbitFlow.Core.Domain.RuleConditionGroup", "Group")
                        .WithMany("Conditions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("QbitFlow.Core.Domain.RuleConditionGroup", b =>
                {
                    b.HasOne("QbitFlow.Core.Domain.RuleConditionGroup", "ParentGroup")
                        .WithMany("Children")
                        .HasForeignKey("ParentGroupId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ParentGroup");
                });

            modelBuilder.Entity("QbitFlow.Core.Domain.RunRuleResult", b =>
                {
                    b.HasOne("QbitFlow.Core.Domain.RunHistory", "Run")
                        .WithMany("RuleResults")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("QbitFlow.Core.Domain.MediaItem", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("SourceStats");
                });

            modelBuilder.Entity("QbitFlow.Core.Domain.Rule", b =>
                {
                    b.Navigation("Action");
                });

            modelBuilder.Entity("QbitFlow.Core.Domain.RuleConditionGroup", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Conditions");
                });

            modelBuilder.Entity("QbitFlow.Core.Domain.RunHistory", b =>
                {
                    b.Navigation("RuleResults");
                });
#pragma warning restore 612, 618
        }
    }
}
