"""Every field a condition can use, derived from the snapshot schema itself.

The list is generated by introspecting a freshly created snapshot database and
the UDF registry, then enriched with authored labels and descriptions. That
ordering matters: a hand-maintained list drifts the moment a column is added or
renamed, and the field reference panel starts advertising fields that do not
exist. Here, a column that loses its documentation still appears (with a
generated description), and a documented field whose column has gone is caught by
a test.

The registry is the single contract between the engine and the UI. The visual
builder's dropdown, the field reference panel, the SQL compiler's type rules and
the raw-SQL autocomplete all read from it.
"""

from __future__ import annotations

import sqlite3
from dataclasses import dataclass, field
from functools import lru_cache

from qbitflow.domain import ConditionOperator, FieldType
from qbitflow.snapshot.schema import create_schema
from qbitflow.snapshot.udf import FUNCTION_DOCS

#: Alias for the driving table in every compiled query.
TORRENT_ALIAS = "t"

#: Joins a field may require, by name. Emitted at most once each, in this order.
JOINS: dict[str, str] = {
    "media": "LEFT JOIN media_items m ON m.id = t.media_item_id",
    "play": "LEFT JOIN play_counts pc ON pc.media_item_id = t.media_item_id",
}


@dataclass(frozen=True, slots=True)
class FieldDef:
    key: str
    label: str
    type: FieldType
    group: str
    description: str
    sample: str
    #: SQL expression this field compiles to, already qualified with its alias.
    expr: str
    joins: tuple[str, ...] = ()
    #: Expression to use for case-insensitive string comparison, when a
    #: pre-lowered indexed column exists.
    ci_expr: str | None = None
    #: When set, the field takes an argument -- for example a storage path name --
    #: and ``expr`` contains one placeholder for it.
    qualifier_label: str | None = None
    nullable: bool = False
    #: Comma-wrapped list columns are tested with a token match, not LIKE.
    is_token_list: bool = False

    @property
    def comparison_expr(self) -> str:
        return self.ci_expr or self.expr

    @property
    def takes_qualifier(self) -> bool:
        return self.qualifier_label is not None


# --------------------------------------------------------------------------- #
# Authored metadata. Keyed by (table, column); anything not listed still becomes
# a field, with a generated description.
# --------------------------------------------------------------------------- #

_TORRENT_DOCS: dict[str, tuple[str, str, str]] = {
    "name": ("Name", "Torrent name as qBittorrent shows it", "The.Big.Film.2019.1080p"),
    "source_name": ("Instance", "Which qBittorrent instance this torrent is on", "main-qbt"),
    "category": ("Category", "qBittorrent category, empty when uncategorised", "Movies"),
    "tags": ("Tags", "Tags on the torrent", "hd, seed"),
    "tag_count": ("Tag count", "How many tags the torrent carries", "2"),
    "save_path": ("Save path", "Directory qBittorrent saves into", "/downloads/movies"),
    "content_path": ("Content path", "Path to the torrent's file or folder", "/downloads/f.mkv"),
    "state": ("State", "qBittorrent state string", "uploading"),
    "is_complete": ("Is complete", "Download has finished", "true"),
    "is_paused": ("Is paused", "Torrent is paused or stopped", "false"),
    "size": ("Size (bytes)", "Total size in bytes", "8589934592"),
    "size_gb": ("Size (GB)", "Total size in gigabytes", "8.0"),
    "downloaded": ("Downloaded", "Bytes downloaded", "8589934592"),
    "uploaded": ("Uploaded", "Bytes uploaded", "17179869184"),
    "uploaded_gb": ("Uploaded (GB)", "Gigabytes uploaded", "16.0"),
    "progress": ("Progress", "Completion from 0 to 1", "1.0"),
    "ratio": ("Ratio", "Share ratio", "2.5"),
    "download_limit": ("Download limit", "Per-torrent limit in bytes/sec, 0 = unlimited", "0"),
    "upload_limit": ("Upload limit", "Per-torrent limit in bytes/sec, 0 = unlimited", "0"),
    "download_speed": ("Download speed", "Current speed in bytes/sec", "0"),
    "upload_speed": ("Upload speed", "Current speed in bytes/sec", "524288"),
    "num_seeds": ("Seeds", "Connected seeds", "4"),
    "num_leechs": ("Leechers", "Connected leechers", "1"),
    "num_complete": ("Swarm seeds", "Seeds in the swarm", "40"),
    "num_incomplete": ("Swarm leechers", "Leechers in the swarm", "3"),
    "active_time_days": ("Active days", "Days the torrent has been active", "14.2"),
    "seeding_time_days": ("Seeding days", "Days spent seeding", "12.0"),
    # The raw seconds are kept alongside the day figures so a rule can be written
    # against whichever unit reads more naturally at the threshold it needs.
    "active_time_seconds": (
        "Active time (seconds)",
        "Seconds the torrent has been active; prefer the day figure for readability",
        "1227000",
    ),
    "seeding_time_seconds": (
        "Seeding time (seconds)",
        "Seconds spent seeding; prefer the day figure for readability",
        "1036800",
    ),
    "availability": ("Availability", "Fraction of the torrent available in the swarm", "1.0"),
    "tracker": ("Tracker", "Current tracker URL", "https://tracker.example/announce"),
    "days_since_added": ("Days since added", "Days since the torrent was added", "104.3"),
    "days_since_completed": (
        "Days since completed",
        "Days since the download finished; empty if it never did",
        "103.1",
    ),
    "days_since_activity": ("Days since activity", "Days since any upload or download", "0.5"),
    "force_start": ("Force start", "Force-start is enabled", "false"),
    "auto_managed": ("Auto-managed", "qBittorrent manages this torrent's location", "true"),
    "super_seeding": ("Super seeding", "Super-seeding is enabled", "false"),
    "mount": ("Mount", "Filesystem the save path lives on", "/mnt/media"),
    "mount_used_percent": (
        "Mount used %",
        "Percent used of the drive this torrent is on -- portable across setups, "
        "unlike naming a specific storage path",
        "87.4",
    ),
    "mount_free_percent": ("Mount free %", "Percent free of the drive this torrent is on", "12.6"),
    "mount_free_bytes": (
        "Mount free bytes",
        "Free bytes on the drive this torrent is on",
        "1.2e11",
    ),
    "mount_total_bytes": ("Mount total bytes", "Size of the drive this torrent is on", "2.0e12"),
    "match_confidence": (
        "Match confidence",
        "How certain the library match is, 0 to 1; empty when nothing matched",
        "1.0",
    ),
    "match_strategy": ("Match strategy", "How the library match was made", "filename"),
}

_MEDIA_DOCS: dict[str, tuple[str, str, str]] = {
    "title": ("Media title", "Title of the matched library item", "The Big Film"),
    "media_type": ("Media type", "movie, show or episode", "movie"),
    "year": ("Media year", "Release year", "2019"),
    "rating": ("Media rating", "Library's own rating, usually out of 10", "8.1"),
    "audience_rating": ("Audience rating", "Audience or critic score where reported", "7.4"),
    "user_rating": ("Your rating", "Your own star rating, where the service exposes it", "9.0"),
    "content_rating": ("Content rating", "Age classification", "PG-13"),
    "genres": ("Genres", "Genres on the library item", "action, drama"),
    "duration_minutes": ("Duration (min)", "Runtime in minutes", "142.0"),
    "days_since_added": ("Media days since added", "Days since it entered the library", "300.0"),
    "series_title": ("Series title", "Parent series, for episodes", "Some Show"),
    "season": ("Season", "Season number", "1"),
    "episode": ("Episode", "Episode number", "4"),
    "source_names": ("Media sources", "Which libraries reported this item", "plex, jellyfin"),
    "watch_total": ("Watch total", "Plays summed across every source", "5"),
    "days_since_last_watched": (
        "Days since watched",
        "Days since the most recent play anywhere; empty if never watched",
        "45.2",
    ),
    "watch_popularity": (
        "Watch popularity",
        "0 to 1 rank of play count among items of the same media type",
        "0.62",
    ),
}

_PLAY_DOCS: dict[str, tuple[str, str, str]] = {
    "total_plays": ("Total plays", "Plays summed across every source", "5"),
    "source_count": ("Reporting sources", "How many sources reported a play", "2"),
    "days_since_played": ("Days since played", "Days since the most recent play", "45.2"),
    "plays_week": ("Plays this week", "Plays in the last 7 days, where reported", "0"),
    "plays_month": ("Plays this month", "Plays in the last 30 days, where reported", "1"),
    "plays_year": ("Plays this year", "Plays in the last 365 days, where reported", "3"),
}

_STORAGE_DOCS: dict[str, tuple[str, str, str]] = {
    "used_percent": ("Storage used %", "Percent used of a named storage path", "87.5"),
    "free_percent": ("Storage free %", "Percent free of a named storage path", "12.5"),
    "free_gb": ("Storage free GB", "Free gigabytes on a named storage path", "125.0"),
    "used_gb": ("Storage used GB", "Used gigabytes on a named storage path", "875.0"),
    "total_gb": ("Storage total GB", "Size of a named storage path in gigabytes", "1000.0"),
    "folder_size_gb": (
        "Folder size GB",
        "Recursive size of the folder, when folder measurement is enabled",
        "412.7",
    ),
    "available": ("Storage available", "Whether the path exists and could be read", "true"),
}

#: Columns that exist for the compiler's benefit and would only confuse a user.
_HIDDEN_COLUMNS = frozenset(
    {
        "hash",
        "source_id",
        "name_lower",
        "category_lower",
        "save_path_key",
        "content_path_key",
        "media_key",
        "media_item_id",
        "id",
        "match_key",
        "title_key",
        "name_key",
        "path_key",
        "added_on",
        "completion_on",
        "last_activity",
        "last_seen_complete",
        "last_watched_at",
        "added_at",
        "last_played_at",
        "total_size",
        "amount_left",
        "priority",
        "eta_seconds",
        "duration_ms",
        "plays_all",
    }
)

#: Columns declared INTEGER that hold 0/1 rather than a count.
_BOOLEAN_COLUMNS = frozenset(
    {
        "is_complete",
        "is_paused",
        "force_start",
        "auto_managed",
        "super_seeding",
        "available",
    }
)

_LIST_COLUMNS = frozenset({"tags", "genres", "source_names"})

#: Where a pre-lowered, indexed column exists, string comparison uses it so the
#: index is still usable. Otherwise the compiler falls back to LOWER().
_CI_COLUMNS = {
    ("torrents", "name"): "t.name_lower",
    ("torrents", "category"): "t.category_lower",
}


def _sql_type_to_field_type(column: str, declared: str) -> FieldType:
    if column in _BOOLEAN_COLUMNS:
        return FieldType.BOOL
    if column in _LIST_COLUMNS:
        return FieldType.LIST
    declared = declared.upper()
    if declared in {"INTEGER", "REAL"}:
        return FieldType.NUMBER
    return FieldType.STRING


def _introspect(table: str) -> list[tuple[str, str, bool]]:
    """(column, declared type, nullable) for one snapshot table."""
    conn = sqlite3.connect(":memory:")
    try:
        create_schema(conn)
        rows = conn.execute(f"PRAGMA table_info({table})").fetchall()
    finally:
        conn.close()
    return [(r[1], r[2], not r[3]) for r in rows]


def _build_group(
    *,
    table: str,
    alias: str,
    prefix: str,
    group: str,
    docs: dict[str, tuple[str, str, str]],
    joins: tuple[str, ...] = (),
) -> list[FieldDef]:
    fields: list[FieldDef] = []
    for column, declared, nullable in _introspect(table):
        if column in _HIDDEN_COLUMNS:
            continue
        field_type = _sql_type_to_field_type(column, declared)
        label, description, sample = docs.get(
            column,
            (
                column.replace("_", " ").capitalize(),
                f"{table}.{column}",
                "",
            ),
        )
        expr = f"{alias}.{column}"
        fields.append(
            FieldDef(
                key=f"{prefix}.{column}",
                label=label,
                type=field_type,
                group=group,
                description=description,
                sample=sample,
                expr=expr,
                joins=joins,
                ci_expr=_CI_COLUMNS.get((table, column)),
                nullable=nullable,
                is_token_list=column in _LIST_COLUMNS,
            )
        )
    return fields


def _storage_fields() -> list[FieldDef]:
    """Storage columns, each taking the path's name as an argument.

    Compiles to a scalar subquery so ``storage["downloads"].used_percent > 85``
    reads as one comparison rather than forcing the user to write a join.
    """
    fields: list[FieldDef] = []
    for column, declared, _ in _introspect("storage_paths"):
        if column in _HIDDEN_COLUMNS or column in {"name", "path", "error", "filesystem",
                                                   "mountpoint", "used_bytes", "free_bytes",
                                                   "total_bytes", "folder_size_bytes"}:
            continue
        label, description, sample = _STORAGE_DOCS.get(
            column, (column.replace("_", " ").capitalize(), f"storage_paths.{column}", "")
        )
        fields.append(
            FieldDef(
                key=f"storage.{column}",
                label=label,
                type=_sql_type_to_field_type(column, declared),
                group="Storage",
                description=description,
                sample=sample,
                expr=f"(SELECT sp.{column} FROM storage_paths sp WHERE sp.name_key = ?)",
                qualifier_label="Storage path name",
                nullable=True,
            )
        )
    return fields


def _aggregate_fields() -> list[FieldDef]:
    """Fields that reach related rows through an aggregate subquery.

    These are what make cross-source questions expressible -- "the most recent
    play across every Tautulli or Jellystat instance" is a MIN over the whole
    watch history for the matched item, not a column on any one row.
    """
    return [
        FieldDef(
            key="watch.min_days_since_played",
            label="Days since any play",
            type=FieldType.NUMBER,
            group="Watch history",
            description=(
                "Days since the most recent play across every source that reported one. "
                "Empty when no source has ever reported a play."
            ),
            sample="92.4",
            expr=(
                "(SELECT MIN(w.days_since_played) FROM watch_history w"
                " WHERE w.media_item_id = t.media_item_id)"
            ),
            nullable=True,
        ),
        FieldDef(
            key="watch.reporting_sources",
            label="Sources reporting plays",
            type=FieldType.NUMBER,
            group="Watch history",
            description="How many distinct sources have reported a play for this item",
            sample="2",
            expr=(
                "(SELECT COUNT(DISTINCT w.source_id) FROM watch_history w"
                " WHERE w.media_item_id = t.media_item_id AND w.play_count > 0)"
            ),
        ),
        FieldDef(
            key="watch.plays_any_source",
            label="Plays (any source)",
            type=FieldType.NUMBER,
            group="Watch history",
            description="Plays summed over every source's history rows",
            sample="7",
            expr=(
                "(SELECT COALESCE(SUM(w.play_count), 0) FROM watch_history w"
                " WHERE w.media_item_id = t.media_item_id)"
            ),
        ),
        FieldDef(
            key="torrent.file_count",
            label="File count",
            type=FieldType.NUMBER,
            group="Torrent",
            description=(
                "Files in the torrent. Requires 'fetch file lists' on the qBittorrent source; "
                "reads 0 otherwise."
            ),
            sample="24",
            expr=(
                "(SELECT COUNT(*) FROM torrent_files f"
                " WHERE f.source_id = t.source_id AND f.torrent_hash = t.hash)"
            ),
        ),
        FieldDef(
            key="torrent.largest_file_gb",
            label="Largest file (GB)",
            type=FieldType.NUMBER,
            group="Torrent",
            description="Size of the biggest file in the torrent, in gigabytes",
            sample="7.8",
            expr=(
                "(SELECT MAX(f.size_gb) FROM torrent_files f"
                " WHERE f.source_id = t.source_id AND f.torrent_hash = t.hash)"
            ),
            nullable=True,
        ),
        FieldDef(
            key="media.is_matched",
            label="Matched to library",
            type=FieldType.BOOL,
            group="Media",
            description="Whether this torrent was linked to a library item at all",
            sample="true",
            expr="(CASE WHEN t.media_item_id IS NULL THEN 0 ELSE 1 END)",
        ),
    ]


@dataclass(frozen=True, slots=True)
class FieldRegistry:
    fields: dict[str, FieldDef] = field(default_factory=dict)

    def get(self, key: str) -> FieldDef | None:
        return self.fields.get(key)

    def by_group(self) -> dict[str, list[FieldDef]]:
        grouped: dict[str, list[FieldDef]] = {}
        for definition in self.fields.values():
            grouped.setdefault(definition.group, []).append(definition)
        for items in grouped.values():
            items.sort(key=lambda f: f.label.lower())
        return dict(sorted(grouped.items()))

    def operators_for(self, field_type: FieldType) -> list[ConditionOperator]:
        return list(OPERATORS_BY_TYPE.get(field_type, ()))


#: Which operators the UI offers per field type. Served to the browser rather
#: than duplicated in JavaScript, so the two cannot drift apart.
OPERATORS_BY_TYPE: dict[FieldType, tuple[ConditionOperator, ...]] = {
    FieldType.NUMBER: (
        ConditionOperator.EQ,
        ConditionOperator.NEQ,
        ConditionOperator.GT,
        ConditionOperator.GTE,
        ConditionOperator.LT,
        ConditionOperator.LTE,
        ConditionOperator.IN_LIST,
        ConditionOperator.IS_NULL,
        ConditionOperator.IS_NOT_NULL,
    ),
    FieldType.STRING: (
        ConditionOperator.EQ,
        ConditionOperator.NEQ,
        ConditionOperator.CONTAINS,
        ConditionOperator.NOT_CONTAINS,
        ConditionOperator.STARTS_WITH,
        ConditionOperator.ENDS_WITH,
        ConditionOperator.MATCHES,
        ConditionOperator.NOT_MATCHES,
        ConditionOperator.IN_LIST,
        ConditionOperator.NOT_IN_LIST,
        ConditionOperator.IS_NULL,
        ConditionOperator.IS_NOT_NULL,
    ),
    FieldType.BOOL: (ConditionOperator.IS_TRUE, ConditionOperator.IS_FALSE),
    FieldType.LIST: (
        ConditionOperator.CONTAINS,
        ConditionOperator.NOT_CONTAINS,
        ConditionOperator.IN_LIST,
        ConditionOperator.NOT_IN_LIST,
    ),
    FieldType.DATETIME: (
        ConditionOperator.OLDER_THAN_DAYS,
        ConditionOperator.NEWER_THAN_DAYS,
        ConditionOperator.IS_NULL,
        ConditionOperator.IS_NOT_NULL,
    ),
    FieldType.DURATION: (
        ConditionOperator.GT,
        ConditionOperator.GTE,
        ConditionOperator.LT,
        ConditionOperator.LTE,
    ),
}


@lru_cache(maxsize=1)
def get_registry() -> FieldRegistry:
    definitions: list[FieldDef] = []
    definitions += _build_group(
        table="torrents", alias="t", prefix="torrent", group="Torrent", docs=_TORRENT_DOCS
    )
    definitions += _build_group(
        table="media_items",
        alias="m",
        prefix="media",
        group="Media",
        docs=_MEDIA_DOCS,
        joins=("media",),
    )
    definitions += _build_group(
        table="play_counts",
        alias="pc",
        prefix="plays",
        group="Watch history",
        docs=_PLAY_DOCS,
        joins=("play",),
    )
    definitions += _storage_fields()
    definitions += _aggregate_fields()
    return FieldRegistry({d.key: d for d in definitions})


def helper_functions() -> dict[str, str]:
    """The UDFs a raw-SQL condition may call, for the reference panel."""
    return dict(FUNCTION_DOCS)
