"""initial schema

Revision ID: f219b5d1be11
Revises: 
Create Date: 2026-09-04 13:57:06.182538
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import qbitflow.db.types  # noqa: F401 - referenced by rendered column types

revision: str = 'f219b5d1be11'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', qbitflow.db.types.UtcTimestamp(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('condition_mode', sa.Enum('builder', 'raw_sql', name='conditionmode', native_enum=False, length=32), nullable=False),
    sa.Column('condition_tree', sa.JSON(), nullable=True),
    sa.Column('raw_sql', sa.Text(), nullable=True),
    sa.Column('compiled_sql', sa.Text(), nullable=True),
    sa.Column('compiled_params', sa.JSON(), nullable=True),
    sa.Column('compile_valid', sa.Boolean(), nullable=False),
    sa.Column('compile_error', sa.Text(), nullable=True),
    sa.Column('compiled_at', qbitflow.db.types.UtcTimestamp(), nullable=True),
    sa.Column('target_source_ids', sa.JSON(), nullable=False),
    sa.Column('cron', sa.String(length=128), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('dry_run', sa.Boolean(), nullable=True),
    sa.Column('stop_on_match', sa.Boolean(), nullable=True),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', qbitflow.db.types.UtcTimestamp(), nullable=False),
    sa.Column('updated_at', qbitflow.db.types.UtcTimestamp(), nullable=False),
    sa.Column('last_run_at', qbitflow.db.types.UtcTimestamp(), nullable=True),
    sa.Column('last_matched_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rules_order'), ['order'], unique=False)

    op.create_table('run_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.Enum('schedule', 'manual', 'api', 'startup', name='runtrigger', native_enum=False, length=32), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('running', 'succeeded', 'failed', 'cancelled', name='runstatus', native_enum=False, length=32), nullable=False),
    sa.Column('started_at', qbitflow.db.types.UtcTimestamp(), nullable=False),
    sa.Column('finished_at', qbitflow.db.types.UtcTimestamp(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('torrents_evaluated', sa.Integer(), nullable=False),
    sa.Column('rules_evaluated', sa.Integer(), nullable=False),
    sa.Column('torrents_matched', sa.Integer(), nullable=False),
    sa.Column('actions_applied', sa.Integer(), nullable=False),
    sa.Column('actions_would_apply', sa.Integer(), nullable=False),
    sa.Column('actions_skipped', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_history_started_at'), ['started_at'], unique=False)

    op.create_table('script_run_markers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('torrent_hash', sa.String(length=40), nullable=False),
    sa.Column('run_dir', sa.String(length=512), nullable=False),
    sa.Column('created_at', qbitflow.db.types.UtcTimestamp(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'torrent_hash', name='uq_script_marker')
    )
    op.create_table('source_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.Enum('qbittorrent', 'plex', 'jellyfin', 'tautulli', 'jellystat', 'jellyglance', 'storage', name='sourcekind', native_enum=False, length=32), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('secret_ciphertext', sa.LargeBinary(), nullable=True),
    sa.Column('secret_nonce', sa.LargeBinary(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('verify_ssl', sa.Boolean(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('created_at', qbitflow.db.types.UtcTimestamp(), nullable=False),
    sa.Column('updated_at', qbitflow.db.types.UtcTimestamp(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('source_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_connections_kind'), ['kind'], unique=False)

    op.create_table('storage_paths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('measure_folder_size', sa.Boolean(), nullable=False),
    sa.Column('folder_scan_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', qbitflow.db.types.UtcTimestamp(), nullable=False),
    sa.Column('updated_at', qbitflow.db.types.UtcTimestamp(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', qbitflow.db.types.UtcTimestamp(), nullable=False),
    sa.Column('updated_at', qbitflow.db.types.UtcTimestamp(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('path_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('from_prefix', sa.String(length=512), nullable=False),
    sa.Column('to_prefix', sa.String(length=512), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('path_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_path_mappings_source_id'), ['source_id'], unique=False)

    op.create_table('rule_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rule_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_actions_rule_id'), ['rule_id'], unique=False)

    op.create_table('run_log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('timestamp', qbitflow.db.types.UtcTimestamp(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('torrent_hash', sa.String(length=40), nullable=True),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['run_history.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_log_entries', schema=None) as batch_op:
        batch_op.create_index('ix_run_log_entries_run_seq', ['run_id', 'seq'], unique=False)

    op.create_table('run_rule_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('rule_name', sa.String(length=128), nullable=False),
    sa.Column('matched_count', sa.Integer(), nullable=False),
    sa.Column('actions_applied', sa.Integer(), nullable=False),
    sa.Column('actions_would_apply', sa.Integer(), nullable=False),
    sa.Column('actions_skipped', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['run_history.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_rule_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_rule_results_run_id'), ['run_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', qbitflow.db.types.UtcTimestamp(), nullable=False),
    sa.Column('expires_at', qbitflow.db.types.UtcTimestamp(), nullable=False),
    sa.Column('last_seen_at', qbitflow.db.types.UtcTimestamp(), nullable=False),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_expires_at'))

    op.drop_table('sessions')
    with op.batch_alter_table('run_rule_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_rule_results_run_id'))

    op.drop_table('run_rule_results')
    with op.batch_alter_table('run_log_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_run_log_entries_run_seq')

    op.drop_table('run_log_entries')
    with op.batch_alter_table('rule_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_actions_rule_id'))

    op.drop_table('rule_actions')
    with op.batch_alter_table('path_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_path_mappings_source_id'))

    op.drop_table('path_mappings')
    op.drop_table('users')
    op.drop_table('storage_paths')
    with op.batch_alter_table('source_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_connections_kind'))

    op.drop_table('source_connections')
    op.drop_table('script_run_markers')
    with op.batch_alter_table('run_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_history_started_at'))

    op.drop_table('run_history')
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rules_order'))

    op.drop_table('rules')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
