using System.Collections.Concurrent;
using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.Data.Sqlite;
using Qbitflow.Core.Domain;

namespace Qbitflow.Snapshot;

/// <summary>
/// DDL and user-defined functions for the in-memory snapshot database.
///
/// The schema is addressed by source, not by shape: there is one table per
/// <see cref="SourceType"/>, named after it in lowercase, plus a "storage" table for
/// configured storage paths. That is what makes a rule's field key
/// <c>&lt;type&gt;.&lt;instance&gt;.&lt;field&gt;</c> resolve directly -- "jellyfin.jellyfin1.title"
/// is the <c>title</c> column of the <c>jellyfin</c> table where <c>instance = 'jellyfin1'</c>.
///
/// Every media/history table shares one wide shape with a <c>kind</c> column, so a source that
/// reports both library items and playback events (Plex can) needs no schema change -- the
/// columns that don't apply to a row are simply NULL. The DDL is generated by looping over the
/// enum, so adding a source type means adding an enum value and an adapter, nothing here.
/// </summary>
internal static class SnapshotSchema
{
    /// <summary>Value of the <c>kind</c> column for a media-library item.</summary>
    public const string KindMedia = "media";

    /// <summary>Value of the <c>kind</c> column for a playback/watch event.</summary>
    public const string KindHistory = "history";

    /// <summary>
    /// Compiled regexes for the <c>regexp</c> UDF, keyed by pattern string. The per-row
    /// callback runs once per torrent per rule, so recompiling would show up in the
    /// 10k-torrent benchmark; pattern cardinality is bounded by the number of rules, so
    /// this is never evicted.
    /// </summary>
    private static readonly ConcurrentDictionary<string, Regex> RegexCache = new();

    private static Regex CompileRegex(string pattern) => RegexCache.GetOrAdd(pattern, static p =>
        new Regex(p, RegexOptions.IgnoreCase | RegexOptions.CultureInvariant, TimeSpan.FromSeconds(1)));

    private const string QbittorrentDdl = """
        CREATE TABLE qbittorrent (
            instance_id INTEGER NOT NULL,
            instance TEXT NOT NULL,
            hash TEXT NOT NULL,
            name TEXT NOT NULL,
            category TEXT,
            tags TEXT,
            save_path TEXT,
            content_path TEXT,
            path_key TEXT,
            size_bytes INTEGER NOT NULL,
            progress REAL NOT NULL,
            state TEXT,
            downloaded_bytes INTEGER NOT NULL,
            uploaded_bytes INTEGER NOT NULL,
            ratio REAL NOT NULL,
            added_on TEXT,
            completion_on TEXT,
            upload_limit_bps INTEGER NOT NULL,
            download_limit_bps INTEGER NOT NULL,
            tracker TEXT,
            total_size_bytes INTEGER NOT NULL,
            amount_left_bytes INTEGER NOT NULL,
            completed_bytes INTEGER NOT NULL,
            dl_speed_bps INTEGER NOT NULL,
            up_speed_bps INTEGER NOT NULL,
            eta_seconds INTEGER NOT NULL,
            seeding_time_seconds INTEGER NOT NULL,
            active_time_seconds INTEGER NOT NULL,
            connected_seeds INTEGER NOT NULL,
            total_seeds INTEGER NOT NULL,
            connected_leechers INTEGER NOT NULL,
            total_leechers INTEGER NOT NULL,
            availability REAL NOT NULL,
            auto_tmm INTEGER NOT NULL,
            ratio_limit REAL NOT NULL,
            seeding_time_limit_minutes INTEGER NOT NULL,
            last_activity TEXT,
            seen_complete TEXT,
            PRIMARY KEY (instance_id, hash)
        );
        CREATE INDEX ix_qbittorrent_path_key ON qbittorrent(path_key);
        CREATE INDEX ix_qbittorrent_instance ON qbittorrent(instance);
        CREATE INDEX ix_qbittorrent_category ON qbittorrent(category);
        CREATE INDEX ix_qbittorrent_state ON qbittorrent(state);
        CREATE INDEX ix_qbittorrent_tracker ON qbittorrent(tracker);

        CREATE TABLE qbittorrent_files (
            instance_id INTEGER NOT NULL,
            torrent_hash TEXT NOT NULL,
            file_path TEXT NOT NULL,
            path_key TEXT,
            size_bytes INTEGER NOT NULL,
            progress REAL NOT NULL
        );
        CREATE INDEX ix_qbittorrent_files_hash ON qbittorrent_files(instance_id, torrent_hash);
        CREATE INDEX ix_qbittorrent_files_path_key ON qbittorrent_files(path_key);
        """;

    private const string StorageDdl = """
        CREATE TABLE storage (
            storage_path_id INTEGER PRIMARY KEY,
            instance TEXT NOT NULL,
            path TEXT NOT NULL,
            available INTEGER NOT NULL,
            error TEXT,
            total_bytes INTEGER NOT NULL,
            used_bytes INTEGER NOT NULL,
            free_bytes INTEGER NOT NULL,
            used_percent REAL NOT NULL,
            free_percent REAL NOT NULL,
            folder_size_bytes INTEGER,
            folder_size_computed_at TEXT
        );
        CREATE INDEX ix_storage_instance ON storage(instance);
        """;

    /// <summary>
    /// The shared wide shape every media/history source type gets. The composite path_key index
    /// leads with path_key because that is what every correlation to a torrent seeks on, and
    /// carries kind/instance so the per-type, per-instance filters are covered by the same index.
    /// </summary>
    private static string MediaHistoryDdl(string table) => $"""
        CREATE TABLE {table} (
            instance_id INTEGER NOT NULL,
            instance TEXT NOT NULL,
            kind TEXT NOT NULL,
            external_key TEXT,
            title TEXT,
            media_type TEXT,
            file_path TEXT,
            path_key TEXT,
            added_at TEXT,
            user_name TEXT,
            watched_at TEXT,
            percent_complete REAL
        );
        CREATE INDEX ix_{table}_path_key ON {table}(path_key, kind, instance);
        CREATE INDEX ix_{table}_instance ON {table}(instance);
        """;

    /// <summary>The table name for a source type -- identical to its field-key type segment.</summary>
    public static string TableFor(SourceType type) => SourceNaming.TypeKey(type);

    public static string BuildDdl()
    {
        var sb = new StringBuilder();
        sb.AppendLine(QbittorrentDdl).AppendLine();
        foreach (var type in SourceNaming.MediaHistoryTypes)
        {
            sb.AppendLine(MediaHistoryDdl(TableFor(type))).AppendLine();
        }
        sb.AppendLine(StorageDdl);
        return sb.ToString();
    }

    public static void CreateSchema(SqliteConnection connection)
    {
        using var command = connection.CreateCommand();
        command.CommandText = BuildDdl();
        command.ExecuteNonQuery();
    }

    public static void RegisterFunctions(SqliteConnection connection)
    {
        // days_since(iso8601_timestamp) -> days between now and that timestamp, or NULL.
        connection.CreateFunction<string?, double?>("days_since", isoTimestamp =>
        {
            if (string.IsNullOrEmpty(isoTimestamp))
            {
                return null;
            }
            return DateTimeOffset.TryParse(isoTimestamp, CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind, out var dt)
                ? (DateTimeOffset.UtcNow - dt).TotalDays
                : null;
        });

        // size_gb(bytes) -> bytes expressed in GB (decimal, 1e9), or NULL.
        connection.CreateFunction<long?, double?>("size_gb", bytes => bytes.HasValue ? bytes.Value / 1_000_000_000.0 : null);

        // path_matches(a, b) -> 1 if the two normalized path_keys are equal or one contains
        // the other (a torrent's content_path may be a parent folder of a media file's path).
        connection.CreateFunction<string?, string?, long>("path_matches", (a, b) =>
        {
            if (string.IsNullOrEmpty(a) || string.IsNullOrEmpty(b))
            {
                return 0;
            }
            if (string.Equals(a, b, StringComparison.Ordinal))
            {
                return 1;
            }
            return a.StartsWith(b, StringComparison.Ordinal) || b.StartsWith(a, StringComparison.Ordinal) ? 1 : 0;
        });

        // regexp(pattern, input) -> 1 if input matches the .NET regex pattern, 0 if not,
        // NULL if either argument is NULL. SQLite calls this with the pattern first for both
        // `input REGEXP pattern` operator syntax and direct calls. Matching is case-insensitive
        // (an inline (?-i) in the pattern forces case-sensitivity). An invalid pattern or a
        // match that exceeds the 1s timeout throws, surfacing as a SQLite error at rule-run time.
        connection.CreateFunction<string?, string?, long?>("regexp", (pattern, input) =>
        {
            if (pattern is null || input is null)
            {
                return null;
            }
            return CompileRegex(pattern).IsMatch(input) ? 1L : 0L;
        });
    }
}
