<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\QbitFlow.Core\QbitFlow.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Json5Core" Version="1.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection" Version="9.0.19" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.Extensions" Version="9.0.19" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.19" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
